name: home_star_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version info
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# Custom Flutter Assets Generator (if using flutter_assets package)
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/themes
  filename: assets.dart
